### ISSUE TITLE
Please add command line flags to purge database entries

### ISSUE THREAD

**Issue by slicer69** [janpascal/denyhosts_sync#12]
Sometimes IP addresses in the database might be considered stale or test data might no longer be needed. In these cases it would be helpful to have command line parameters which would purge the database of old IP address.

My suggestion would be to have three options:
1. Purge all legacy IP address.
2. Purge all non-legacy IP address
3. Purge one specific IP address from either the legacy or the non-legacy tables.

So for example:
dh_syncserver --purge-legacy
dh_syncserver --purge-addresses
dh_syncserver --purge-ip 123.456.789.012

Alternatively, it might be useful to have the sync server purge old IP address if it receives a signal. For example, sending SIGHUP could re-read the configuration file and purge old IP addresses from the database to give the server a fresh start.

**Comment by janpascal** [comment]
Hi, most of this is implemented now. Though I'm opposed to purging IP addresses from a SIGHUP, since this will give concurrency issues when the addresses are purged while a client is adding a report. I did implement a sighup handler that re-reads the configuration file.

@slicer69, could you test if these commits fix your issue?

**Comment by slicer69** [comment]
All of the command line parameters and SIGHUP appear to work as intended. Thank you.
