### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by adriel** [janpascal/denyhosts_sync#41]
I've switched over to the Python 3 code today, but system usage seems similar so have spent some time on the DB (MariaDB/MySQL) and have managed to tweak some of the settings to (mostly `--innodb-buffer-pool-size=5G`), which has resolved the massive HDD usage I was getting https://github.com/denyhosts/denyhosts/issues/149#issuecomment-926174223.

But not sure how to debug the the remaining CPU usage. As seen by the screenshots below, it appears the majority is from `denyhosts_sync`.

Also, worth noting is that I've tried running the sync server with an empty db, which results in near 0 CPU usage, which suggests there being an issue with the large DB (~3GB). (though this was only run for 10 mins)
Just found https://github.com/janpascal/denyhosts_sync/issues/39 now too, which looks like there are `SELECT *` being used, which I'd imagine wouldn't help the CPU load.

Let me know what you need to help debug the issue.

![image](https://user-images.githubusercontent.com/154217/136732694-4ba46b73-bab1-4dc9-a3a3-5779b7ff6410.png)
![image](https://user-images.githubusercontent.com/154217/136732711-4cc10b17-e1db-46fb-97bb-8585d5450a9f.png)
![image](https://user-images.githubusercontent.com/154217/136732736-992553da-8cee-4af2-b84f-edd21babd882.png)

![image](https://user-images.githubusercontent.com/154217/136744631-ea2bd133-895c-4a66-8e0d-39d44e7961a5.png)

**Comment by LucChoubert** [comment]
Hello Adriel

I am happy to work on that one. I was thinking at what I need in terms of data to start to look at possible optimization.
What I would like to know:
- Number of transaction per sec for the various end points or use cases. If I got it well, this is only:
      - RPC2 over http: get_new_host, add_hosts
      - static files over http: the HTML, CSS, JS & SVG files of the statistic website
      - regular statistics generation: triggered automatically every X min depending on the config
- For all the use cases above, the processing or elapsed time  at various steps of those transactions

Where to get those data ? Ideally (Option 1) from the live system with real traffic to get a first understanding. In a second phase (Option 2) from performance test environment to validate hypothesis, and validate the enhancements.

For Option 1, an easy option, but that requires your support @adriel is for you to activate the debug logs (loglevel: DEBUG) for some time (let's say 1 hours) and then to find a way to send them to me (dedicated git repo ?, send link to any file sharing solution by email ?,...).

For Option 2, a dump of the database in a format that I can reuse to re-import (ideally in both mariaDb and sqlite) would be required because as you mentioned the CPU consumption comes probably from the volume of data. It requires again you support @adriel , with same file sharing solution to identify.

Getting already current log file (few hours of traffic) and the config file would already gives some hints, so happy to get them if you can share them.

**Comment by adriel** [comment]
I think we can close this as you've made the necessary code changes to get the server up and running again. Thank you!
